name: test-gh

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  test-all:
    name: Test GH - Linux
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v1
      with:
        go-version: "1.17"
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: src/github.com/${{ github.repository }}
    - name: Run Tests
      run: |
        set -e -x

        export GOPATH=$(echo `pwd`)
        export PATH="$PATH:$GOPATH/bin"
        cd src/github.com/${{ github.repository }}

        # deploy local registry and run tests
        ./hack/test-all-local-registry.sh

  test-all-windows:
    name: Test GH - Windows
    runs-on: windows-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v1
      with:
        go-version: "1.17"
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: src/github.com/${{ github.repository }}
    - name: Run Tests
      run: |
        SET pwd=%cd%
        [System.Environment]::SetEnvironmentVariable("GOPATH", "%pwd%", "Machine")

        $goroot = [System.Environment]::GetEnvironmentVariable("GOROOT")
        $gopath = [System.Environment]::GetEnvironmentVariable("GOPATH")
        $p = [System.Environment]::GetEnvironmentVariable("PATH", "Machine")
        $p = "$goroot\bin;$gopath\bin;$p"
        [System.Environment]::SetEnvironmentVariable("PATH", "$p", "Machine")

        cd src/github.com/${{ github.repository }}

        [System.Environment]::SetEnvironmentVariable("IMGPKG_E2E_IMAGE", "ttl.sh/github-action-test-relocation-$GITHUB_RUN_ID")
        [System.Environment]::SetEnvironmentVariable("IMGPKG_E2E_RELOCATION_REPO", "ttl.sh/github-action-imgpkg-test-$GITHUB_RUN_ID")
        # deploy local registry and run tests
        bash ./hack/test-all.sh