name: test-gh

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  test-all:
    name: Test GH - Linux
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v1
      with:
        go-version: "1.17"
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: src/github.com/${{ github.repository }}
    - name: Run Tests
      run: |
        set -e -x

        export GOPATH=$(echo `pwd`)
        export PATH="$PATH:$GOPATH/bin"
        cd src/github.com/${{ github.repository }}

        # deploy local registry and run tests
        ./hack/test-all-local-registry.sh

  test-all-windows:
    name: Test GH - Windows
    runs-on: windows-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v1
      with:
        go-version: "1.17"
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: src/github.com/${{ github.repository }}
    - name: Run Tests
      run: |
        bash -c '
        set -e -x

        export GOPATH=$(echo `pwd`)
        export PATH="$GOPATH/bin:$PATH"
        cd src/github.com/${{ github.repository }}

        export IMGPKG_E2E_IMAGE="ttl.sh/github-action-test-relocation-$GITHUB_RUN_ID"
        export IMGPKG_E2E_RELOCATION_REPO="ttl.sh/github-action-imgpkg-test-$GITHUB_RUN_ID"

        go install github.com/sigstore/cosign/cmd/cosign@v0.5.0

        alias cosign=cosign.exe

        export IMGPKG_BINARY_EXT=".exe"
        ./hack/build.sh
        $PWD/imgpkg.exe push -f test/e2e/assets/bundle_file_permissions -b ttl.sh/test-windows-push
        docker pull ttl.sh/test-windows-push
        '